### ISSUE TITLE
English firmware for HS8546V5

### ISSUE THREAD

**Issue by oblitum** [2879597772/ONT#1]
Hi, thanks for this repository.

I'm a person from outside China and I have bought HS8546V5 which came with software version V5R019C20S050.

It's English firmware, but it's defective, I lose connection every couple of minutes. Can you help me find a new English firmware for download?

I have found this but I can't download from outside China:

- https://download.csdn.net/download/liulianxx/12367305

You have newer Chinese firmware on this repository, V500R019C00SPC110, my device original firmware as written in its box was V500R019C00SPC050.

But I need English firmware.

Any help appreciated.

**Comment by oblitum** [comment]
Doesn't matter. I installed Chinese firmware (both V500R019C00SPC110 and V500R019C20SPC050) and still have this issue, this device cannot hold permanent connection longer than an hour, it always disconnects and connect back. WiFi seems to be OK, looks like it has issues with Ethernet.

**Comment by wcyuns** [comment]
I'm sorry, because of Huawei's policy, it's hard for me to find more available firmware
The problem you mentioned may be due to the local network operator's settings. I'm sorry I don't have a better solution
Tips: the above answers are answered by translation software. There may be logical problems. Please understand

**Comment by wcyuns** [comment]
I noticed that you seem to mention the firmware "V500R019C20SPC050". Do you have this firmware? , if so, can it be easily uploaded to the GitHub project for more people to view and download?
Tips: the above answers are answered by translation software. There may be logical problems. Please understand

**Comment by oblitum** [comment]
Hi, I downloaded that firmware from https://download.csdn.net/detail/jinshengen88/12428432.

Also, this is a bug in the ONT device, it's not issue with ISP. Other people confirmed this problem on this thread:

http://www.chinadsl.net/thread-167392-1-1.html

I have other confirmation from other places too.

Today I'm using HS8546V5 as access point because of this bug.
